    - name: Deploy systemd service file for hello_world
      ansible.builtin.copy:
        src: files/hello_world.service
        dest: /etc/systemd/system/hello_world.service
        mode: '0644'
      notify: Reload systemd

    - name: Create directory for systemd override files
      ansible.builtin.file:
        path: /etc/systemd/system/hello_world.service.d
        state: directory
        mode: '0755'

    - name: Deploy systemd override file for hello_world
      ansible.builtin.copy:
        src: files/override.conf
        dest: /etc/systemd/system/hello_world.service.d/override.conf
      notify: Reload systemd

    - name: Deploy systemd timer file for hello_world
      ansible.builtin.copy:
        src: files/hello_world.timer
        dest: /etc/systemd/system/hello_world.timer
        mode: '0644'
      notify: Reload systemd
